import Translator

t = Translator.Translator(srcTrain='../data/train.en',
                          tgtTrain='../data/train.ja',
                          actTrain='../data/train.oracle.en',
                          srcDev='../data/dev.en',
                          tgtDev='../data/dev.ja',
                          actDev='../data/dev.oracle.en',
                          srcVocaThreshold=1,
                          tgtVocaThreshold=1)
t.demo(inputDim=100,
       inputActDim=100,
       hiddenDim=100,
       hiddenEncDim=100,
       hiddenActDim=100,
       scale=1,
       clipThreshold=10,
       beamSize=10,
       maxLen=10,
       miniBatchSize=16,
       threadNum=5,
       learningRate=0.01,
       saveDirName='../save/',
       loadModelName='',
       loadGradName='',
       startIter=5,
       epochs=10)
